---
services:
  plex: #instala plex
    image: lscr.io/linuxserver/plex:latest
    container_name: plexmediaserver
    network_mode: host
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Santiago
      - VERSION=docker
    volumes:
      - /srv/dev-disk-by-uuid-e66deb63-a199-4385-970e-785ba1405328/plex-library/config:/config
      - /srv/dev-disk-by-uuid-e66deb63-a199-4385-970e-785ba1405328/plex-library/series:/tv
      - /srv/dev-disk-by-uuid-e66deb63-a199-4385-970e-785ba1405328/plex-library/peliculas:/movies
    restart: unless-stopped
  
  transmission: #instala transmission
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Santiago
      - USER=torrent #optional
      - PASS=alfredo13 #optional
    volumes:
      - /configs/transmission:/config
      - /transmission/downloads:/downloads
      - /transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
  
  flexget: #instala flexget
    image: lscr.io/linuxserver/flexget:latest
    container_name: flexget
    environment:
      - PUID=1000 #verificar según tu user con id your_user
      - PGID=100 #Verificar con id your_user
      - TZ=America/Santiago
      - FG_LOG_LEVEL=info
      - FG_LOG_FILE=/config/flexget.log 
      - FG_CONFIG_FILE=/config/config.yml #directorio que debe agregarse posteriormente en volumes
      - FG_WEBUI_PASSWORD=*4dm1n12tr@d0r #optional
      - TORRENT_PLUGIN=transmission #Se agrega plugin para agregar torrents a transmission
    volumes:
      - /configs/flexget:/config #directorio donde se almacenarán las configs, previamente compartido en omv.
      - /configs/flexget/custom-cont-init.d:/custom-cont-init.d #opcional, solo si se ejecutaran script de inicio.
      - /transmission/downloads:/downloads #directorio de descargas de transmission, donde se ubica la carpeta completed.
      - /srv/dev-disk-by-uuid-e66deb63-a199-4385-970e-785ba1405328/plex-library/series:/tv #directorio de plex para series
      - /srv/dev-disk-by-uuid-e66deb63-a199-4385-970e-785ba1405328/plex-library/peliculas:/movies #directorio de plex para pelis
    ports:
      - 5050:5050 #puerto para la Web UI
    restart: unless-stopped